### ISSUE TITLE
Implement generic DiagnosticSource listener

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-dotnet#592] opened 2017-07-27 17:07 UTC
Generic DiagnosticsSource listener (may be part of DependencyCollection nuget package) will be helpful to simplify support of a new platforms and technologies.

This work may require implementing a new type of operation - something in between of Requests and Dependencies

**Comment by lmolkova** [comment] 2017-07-27 17:09
Related to https://github.com/Microsoft/ApplicationInsights-dotnet-server/issues/609

**Comment by MS-TimothyMothra** [comment] 2017-11-14 19:16
@lmolkova Is this task finished?

**Comment by lmolkova** [comment] 2017-11-14 19:41
@MS-TimothyMothra I think it's addressed with https://github.com/Microsoft/ApplicationInsights-dotnet-server/pull/662

@TomMilos is behind this work, not me

**Comment by lmolkova** [comment] 2017-11-14 19:41
Perhaps it's a duplicate of https://github.com/Microsoft/ApplicationInsights-dotnet-server/issues/665

**Closed** 2018-04-17 18:55 UTC
Labels: composite-apps, enhancement
