### ISSUE TITLE
Response Code Dimension Empty for Server Requests Standard Metric

### ISSUE THREAD

**Issue by bdschaap** [microsoft/ApplicationInsights-dotnet#1227] opened 2019-09-26 17:57 UTC
The Response Code dimension is empty for the Server Requests and Server Response Time standard metric.  You can see this within the App Insights resource in Azure.  Go to the Metrics blade, choose Standard Metrics, Server requests.  Then click Apply splitting and choose Response code.  It shows <empty>.

I reviewed the telemetry emitted from a sample app and noticed that the telemetry for the Server Response Time metric aggregation is a rolled up number.  It is not categorized by response code.  

Should the App Insights metric aggregation telemetry be categorized by the dimensions that those metrics support?

**Comment by cijothomas** [comment] 2019-09-30 19:22
@bdschaap The built-in metric aggregator lacks any dimensions like response code, role instance etc. Infact it only has a single dimension (sucesss=true/false) for Requests. This is being fixed - i will post an update when i have ETAs.

As a workaround, you can chose LogBased metric instead of Standard metric. It'll have all dimensions, but this data is coming after sampling, so the accuracy is affected by sampling.

**Comment by bdschaap** [comment] 2019-10-01 12:13
Thank you.  I plan to use the dimensions primarily for alerting on metrics.  I'm currently using metrics-based alerts since they support dynamic thresholds.  I could consider using a log-based alert with a static threshold based on a percentage of failed requests or something similar to that.

**Comment by cijothomas** [comment] 2019-10-03 21:31
Until more dimensions are added to these StandardMetrics, log based metric is the best alternative, though it has lower accuracy due to sampling.

Closing this as duplicate of the bigger item:
https://github.com/microsoft/ApplicationInsights-dotnet/issues/1233

**Closed** 2019-10-04 01:27 UTC
Labels: enhancement, metrics
