### ISSUE TITLE
Telemetry item gets lost when property value ends with a backslash

### ISSUE THREAD

**Issue by AndreasMossner** [microsoft/ApplicationInsights-dotnet#2698] opened 2022-10-25 14:43 UTC
The exact same behavior as in issue #[261](https://github.com/microsoft/ApplicationInsights-dotnet/issues/261) has recently surfaced. Our project is missing logs since two weeks ago. Due to the fact, that both the newest Application Insights NuGet package (2.21.0) and (2.20.0) show this behavior, I suspect it's an azure backend bug.

The obivous quick fix, removing ending backslashes, has been implemented at our end. The community will still profit, when this bug is removed, I assume.

**Comment by TimothyMothra** [comment] 2022-10-25 16:44
@AndreasMossner can you share any sample code that reproduces this?

**Comment by AndreasMossner** [comment] 2022-10-26 10:02
You can basically use the code from issue #261. I just updated the telemetry configuration.
```
using Microsoft.ApplicationInsights;
using Microsoft.ApplicationInsights.Extensibility;


TelemetryConfiguration configuration = TelemetryConfiguration.CreateDefault();
configuration.TelemetryChannel.DeveloperMode = true;
configuration.ConnectionString = "**MyConnectionString**";
var telemetryClient = new TelemetryClient(configuration);

var validProps = new Dictionary<string, string>
{
    {"WorksFine", @"`Does_Not_End_With_Backslash\1234567890-=[];',./~!@#$%^&*()_+{}:|<>?"}
};

var failedProps = new Dictionary<string, string>
{
    {"DoesNotWork", @"Testing\"}
};

telemetryClient.TrackEvent("No Properties - This works");
telemetryClient.TrackEvent("Valid Properties - This works", validProps);
telemetryClient.TrackEvent("Failed Properties - Does not work", failedProps);

telemetryClient.Flush();
```

**Comment by AndreasMossner** [comment] 2022-11-03 08:20
@TimothyMothra Have you got a chance to look at it yet?

**Comment by TimothyMothra** [comment] 2022-11-03 17:21
@AndreasMossner The code sample you provided works for me. All three events show in the portal:

![image](https://user-images.githubusercontent.com/28785781/199790760-c70c4b69-57a3-40fc-b56d-e8e28a323444.png)

![image](https://user-images.githubusercontent.com/28785781/199790830-d105684b-20fa-4081-b56e-689f7ce412ae.png)

**Comment by TimothyMothra** [comment] 2022-11-04 17:00
Hi @AndreasMossner, 
We're getting into an area that I can't troubleshoot over github.
Please consider opening an Azure Support Request so that our support teams can help investigate this. https://github.com/microsoft/ApplicationInsights-dotnet#support
You can reference this github issue.

From your screenshot, I can see that the SDK correctly created the Telemetry Item, but that item wasn't ingested. 
I would need to see more detailed logs to understand what's happening here.

--
One last thing you can try is our Ingestion test script: https://github.com/microsoft/ApplicationInsights-dotnet/blob/main/troubleshooting/Ingestion/PostTelemetry.ps1

You can modify line 47 with the extra backslashes:
https://github.com/microsoft/ApplicationInsights-dotnet/blob/35b1a303f0fa07b9d93f178920ec65d400f729c8/troubleshooting/Ingestion/PostTelemetry.ps1#L46-L48

When you run this script, you should provide your connection string like this: `PostTelemetry.ps1 -ConnectionString "<YOUR CONNECTION STRING HERE>"`



When I run this script this is the output:
```
	"properties": {
		"TestProperty": "TestValue\\"
	}
```

```
VERBOSE: POST with 514-byte payload
VERBOSE: received 49-byte response of content type application/json
StatusCode        : 200
StatusDescription : OK
Content           : {"itemsReceived":1,"itemsAccepted":1,"errors":[]}
RawContent        : HTTP/1.1 200 OK
                    x-ms-session-id: FE62A3D3-8089-4EBD-B100-E1199923FB26
                    Strict-Transport-Security: max-age=31536000
                    Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Name, Content-Type,…
Headers           : {[x-ms-session-id, System.String[]], [Strict-Transport-Security, System.String[]], [Access-Control-Allow-Headers, System.String[]],
                    [Access-Control-Allow-Origin, System.String[]]…}
Images            : {}
InputFields       : {}
Links             : {}
RawContentLength  : 49
RelationLink      : {}
```


If I have invalid json, I get a response from Ingestion like this:
```
	"properties": {
		"TestProperty": "TestValue\"
	}
```
```
VERBOSE: POST with 513-byte payload
VERBOSE: received 127-byte response of content type application/json
Invoke-WebRequest: C:\REPOS\AISDK\dotnet\troubleshooting\Ingestion\PostTelemetry.ps1:63:1
Line |
  63 |  Invoke-WebRequest -Uri $Url -Method POST -Body $AvailabilityData -Ver …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | {"itemsReceived":1,"itemsAccepted":0,"errors":[{"index":0,"statusCode":400,"message":"Invalid JSON specified in the request"}]}
```


@AndreasMossner, If you can capture that error message from the Ingestion service that would help narrow down the issue.

**Comment by AndreasMossner** [comment] 2022-11-11 16:02
Hi, I just got the chance to try it.
With the standard json, I have that as an output:
```
VERBOSE: POST with 512-byte payload
VERBOSE: received -byte response of content type application/json

StatusCode        : 200
StatusDescription : OK
Content           : {"itemsReceived":1,"itemsAccepted":1,"errors":[]}
RawContent        : HTTP/1.1 200 OK
                    Transfer-Encoding: chunked
                    Server: Microsoft-HTTPAPI/2.0
                    X-Content-Type-Options: nosniff
                    Strict-Transport-Security: max-age=31536000
                    X-Request-ID: c554b285-b1fb-4c2d-a0aa-e4b57967…
Headers           : {[Transfer-Encoding, System.String[]], [Server, System.String[]], [X-Content-Type-Options,
                    System.String[]], [Strict-Transport-Security, System.String[]]…}
Images            : {}
InputFields       : {}
Links             : {}
RawContentLength  : 49
RelationLink      : {}
```
With `testvalue\\` or `testvalue\`, I get:
```
VERBOSE: POST with 514-byte payload
VERBOSE: received -byte response of content type application/json
Invoke-WebRequest: C:\Repos\TriggerAppInsights\TriggerAppInsight2\IngestAppIns.ps1:63
Line |
  63 |  Invoke-WebRequest -Uri $Url -Method POST -Body $AvailabilityData -Ver …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | {"itemsReceived":1,"itemsAccepted":0,"errors":[{"index":0,"statusCode":400,"message":"Invalid JSON specified in
     | the request"}]}
```

**Comment by TimothyMothra** [comment] 2022-11-14 17:56
@AndreasMossner, this sounds like a bug in the Ingestion Service.
Please open an Azure Support request so their team can investigate this: https://github.com/microsoft/ApplicationInsights-dotnet#support
You can reference this github issue.


Can you please share here the IngestionEndpoint in your connection string?
Example: `IngestionEndpoint=https://westus2-0.in.applicationinsights.azure.com/`

**Comment by AndreasMossner** [comment] 2022-11-15 11:22
The Ingestione Endpoint:
`IngestionEndpoint=https://westeurope-.in.applicationinsights.azure.com/`

I tried to open a support request, but since I apparantly only have a basic plan, it doesn't let me do that.
I don't really get why that's the case, though. Neither does the problem seem to be on my end, nor do I need technical support. I just wanted to report a bug. Sadly, other people also seem to have the same [problem](https://techcommunity.microsoft.com/t5/azure-governance-and-management/what-s-the-best-way-to-report-a-bug/m-p/1184553).

I also don't get why I only have a basic support plan. Although my company has other subscriptions for productive systems, besides the personal visual studio abonnements, I apparantly can't open tickets on one of those.

**Comment by maily89** [comment] 2022-11-15 19:23
Issue acknowledged. Looking into it.

**Comment by zakimaksyutov** [comment] 2022-12-11 06:02
@AndreasMossner, thank you for reporting the issue! We have a fix ready. Since it touches the most exercised path it will take time for us to validate it and roll it out. It should reach West Europe by early Jan (might reach earlier but not guaranteed).

Again, thank you for reporting the issue and providing very clear explanation and simple repro!

**Comment by zakimaksyutov** [comment] 2022-12-16 07:53
The fix is in prod. Thank you for reporting it!

We're in the process of moving to a new backend. The fix for referenced issue from a few years ago did add a unit test for this condition. Unfortunately it wasn't properly ported and as a result we lost this coverage.

**Closed by zakimaksyutov** 2022-12-16 07:53 UTC
Labels: bug
