### ISSUE TITLE
AI: Server telemetry channel was not initialized

### ISSUE THREAD

**Issue by rdagumampan** [Microsoft/ApplicationInsights-dotnet#756] opened 2018-04-07 04:15 UTC
Hi AI Team,

I am trying to instrument my service using AI but I am not getting the server metrics in the server. This TRACE message shows up in the "Search" in AI portal but I can't figure why or how to fix this. The only thing we did special is to override the cloudRoleName using customer initializer so we can see multiple instances of same service in the single application map.

**Trace Message**

```
AI: Server telemetry channel was not initialized. So persistent storage is turned off. You need to call ServerTelemetryChannel.Initialize(). Currently monitoring will continue but if telemetry cannot be sent it will be dropped. 
```

**AI Portal**

Live Metrics shows the server is listed but CPU, RAM etc.. is N/A
Server performance metrics - N/A, NOT OK
Dependencies tracking - OK
Custom events - OK

**package.config**

```
  <package id="Microsoft.ApplicationInsights" version="2.5.1" targetFramework="net461" />
  <package id="Microsoft.ApplicationInsights.Agent.Intercept" version="2.4.0" targetFramework="net461" />
  <package id="Microsoft.ApplicationInsights.DependencyCollector" version="2.5.1" targetFramework="net461" />
  <package id="Microsoft.ApplicationInsights.PerfCounterCollector" version="2.5.1" targetFramework="net461" />
  <package id="Microsoft.ApplicationInsights.WindowsServer" version="2.5.1" targetFramework="net461" />
  <package id="Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel" version="2.5.1" targetFramework="net461" />
```

**Program.cs**

```
//active telemery for application performance monitoring
TelemetryConfiguration.Active.TelemetryInitializers.Add(new ServiceNameInitializer(serviceSettings.ServiceName));
TelemetryConfiguration.Active.DisableTelemetry = !serviceSettings.TelemetryAiEnabled;
TelemetryConfiguration.Active.InstrumentationKey = serviceSettings.TelemetryAiInstrumentationKey;
```

**ServiceNameInitializer**

```
    public class ServiceNameInitializer : ITelemetryInitializer
    {
        private readonly string _serviceName;
        public ServiceNameInitializer(string serviceName)
        {
            _serviceName = serviceName;
        }

        public void Initialize(ITelemetry telemetry)
        {
            telemetry.Context.Cloud.RoleName = _serviceName;
        }
    }
```

**Additional Info:**

I use Serilog sinks into AI and this perhaps explains why the server shows up in the Live Metrics maybe the Server Telemetry actually never worked in my case?

When I run the same service on my local machine, the server perf counters (RAM, CPU, etc) appears in AI portal.

**Comment by SergeyKanzhelev** [comment] 2018-04-10 05:40
What the framework version an application compiled with and running on? Can you post `ApplicationInsights.config`?

From the look of an issue I think it is this: https://github.com/Microsoft/ApplicationInsights-dotnet-server/issues/328 Telemetry disabled, but live metrics do not respect the setting so you got confused.

The only worrisome thing here is why channel wasn't initialized.

**Comment by fisica3** [comment] 2018-04-10 14:35
Hello, I'm having similar issues, I added in my code a Telemetry.TrackEvent("Message"); code and works fine, but the message about "telemetry channel was not initialized" was always there, even before my customization.

This is my ApplicationInsights.config as Visual Studio 2017 added:

``<?xml version="1.0" encoding="utf-8"?>
<ApplicationInsights xmlns="http://schemas.microsoft.com/ApplicationInsights/2013/Settings">
  
  <InstrumentationKey>685fd420-883a-4d2b-9c3b-4a13e2eec1ce</InstrumentationKey>
  <TelemetryInitializers>
    <Add Type="Microsoft.ApplicationInsights.DependencyCollector.HttpDependenciesParsingTelemetryInitializer, Microsoft.AI.DependencyCollector"/>
    <Add Type="Microsoft.ApplicationInsights.WindowsServer.AzureRoleEnvironmentTelemetryInitializer, Microsoft.AI.WindowsServer"/>
    <Add Type="Microsoft.ApplicationInsights.WindowsServer.AzureWebAppRoleEnvironmentTelemetryInitializer, Microsoft.AI.WindowsServer"/>
    <Add Type="Microsoft.ApplicationInsights.WindowsServer.BuildInfoConfigComponentVersionTelemetryInitializer, Microsoft.AI.WindowsServer"/>
    <Add Type="Microsoft.ApplicationInsights.Web.WebTestTelemetryInitializer, Microsoft.AI.Web"/>
    <Add Type="Microsoft.ApplicationInsights.Web.SyntheticUserAgentTelemetryInitializer, Microsoft.AI.Web">
      
      <Filters>search|spider|crawl|Bot|Monitor|AlwaysOn</Filters>
    </Add>
    <Add Type="Microsoft.ApplicationInsights.Web.ClientIpHeaderTelemetryInitializer, Microsoft.AI.Web"/>
    <Add Type="Microsoft.ApplicationInsights.Web.OperationNameTelemetryInitializer, Microsoft.AI.Web"/>
    <Add Type="Microsoft.ApplicationInsights.Web.OperationCorrelationTelemetryInitializer, Microsoft.AI.Web"/>
    <Add Type="Microsoft.ApplicationInsights.Web.UserTelemetryInitializer, Microsoft.AI.Web"/>
    <Add Type="Microsoft.ApplicationInsights.Web.AuthenticatedUserIdTelemetryInitializer, Microsoft.AI.Web"/>
    <Add Type="Microsoft.ApplicationInsights.Web.AccountIdTelemetryInitializer, Microsoft.AI.Web"/>
    <Add Type="Microsoft.ApplicationInsights.Web.SessionTelemetryInitializer, Microsoft.AI.Web"/>
  </TelemetryInitializers>
  <TelemetryModules>
    <Add Type="Microsoft.ApplicationInsights.DependencyCollector.DependencyTrackingTelemetryModule, Microsoft.AI.DependencyCollector">
      <ExcludeComponentCorrelationHttpHeadersOnDomains>
        
        <Add>core.windows.net</Add>
        <Add>core.chinacloudapi.cn</Add>
        <Add>core.cloudapi.de</Add>
        <Add>core.usgovcloudapi.net</Add>
        <Add>localhost</Add>
        <Add>127.0.0.1</Add>
      </ExcludeComponentCorrelationHttpHeadersOnDomains>
      <IncludeDiagnosticSourceActivities>
        <Add>Microsoft.Azure.EventHubs</Add>
        <Add>Microsoft.Azure.ServiceBus</Add>
      </IncludeDiagnosticSourceActivities>
    </Add>
    <Add Type="Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.PerformanceCollectorModule, Microsoft.AI.PerfCounterCollector">
      
    </Add>
    <Add Type="Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.QuickPulse.QuickPulseTelemetryModule, Microsoft.AI.PerfCounterCollector"/>
    <Add Type="Microsoft.ApplicationInsights.WindowsServer.DeveloperModeWithDebuggerAttachedTelemetryModule, Microsoft.AI.WindowsServer"/>
    <Add Type="Microsoft.ApplicationInsights.WindowsServer.UnhandledExceptionTelemetryModule, Microsoft.AI.WindowsServer"/>
    <Add Type="Microsoft.ApplicationInsights.WindowsServer.UnobservedExceptionTelemetryModule, Microsoft.AI.WindowsServer">
      
    </Add>
    <Add Type="Microsoft.ApplicationInsights.Web.RequestTrackingTelemetryModule, Microsoft.AI.Web">
      <Handlers>
        
        <Add>Microsoft.VisualStudio.Web.PageInspector.Runtime.Tracing.RequestDataHttpHandler</Add>
        <Add>System.Web.StaticFileHandler</Add>
        <Add>System.Web.Handlers.AssemblyResourceLoader</Add>
        <Add>System.Web.Optimization.BundleHandler</Add>
        <Add>System.Web.Script.Services.ScriptHandlerFactory</Add>
        <Add>System.Web.Handlers.TraceHandler</Add>
        <Add>System.Web.Services.Discovery.DiscoveryRequestHandler</Add>
        <Add>System.Web.HttpDebugHandler</Add>
      </Handlers>
    </Add>
    <Add Type="Microsoft.ApplicationInsights.Web.ExceptionTrackingTelemetryModule, Microsoft.AI.Web"/>
    <Add Type="Microsoft.ApplicationInsights.Web.AspNetDiagnosticTelemetryModule, Microsoft.AI.Web"/>
  </TelemetryModules>
  <TelemetryProcessors>
    <Add Type="Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.QuickPulse.QuickPulseTelemetryProcessor, Microsoft.AI.PerfCounterCollector"/>
    <Add Type="Microsoft.ApplicationInsights.Extensibility.AutocollectedMetricsExtractor, Microsoft.ApplicationInsights"/>
    <Add Type="Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel.AdaptiveSamplingTelemetryProcessor, Microsoft.AI.ServerTelemetryChannel">
      <MaxTelemetryItemsPerSecond>5</MaxTelemetryItemsPerSecond>
      <ExcludedTypes>Event</ExcludedTypes>
    </Add>
    <Add Type="Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel.AdaptiveSamplingTelemetryProcessor, Microsoft.AI.ServerTelemetryChannel">
      <MaxTelemetryItemsPerSecond>5</MaxTelemetryItemsPerSecond>
      <IncludedTypes>Event</IncludedTypes>
    </Add>
  </TelemetryProcessors>
  <TelemetryChannel Type="Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel.ServerTelemetryChannel, Microsoft.AI.ServerTelemetryChannel"/>
</ApplicationInsights>

**Comment by SergeyKanzhelev** [comment] 2018-04-19 20:24
We figured out that this problem most likely caused by Application Insights Profiler, not Application Insights itself. There is no workaround except waiting for an update for Azure Web App extension.

@pharring do you have an estimation for this to be fixed?

**Comment by AmeetAB** [comment] 2018-05-06 17:38
Hi, is there an update on this? We're experiencing this as well on our production api

**Comment by SergeyKanzhelev** [comment] 2018-05-08 17:33
As far as I know the issue is fixed in code. It's the matter of deployment. @pharring any updates?

**Comment by pharring** [comment] 2018-05-08 18:09
Yes, it's already in the latest Application Insights site extension. Please upgrade the site extension via the Azure Portal or the Kudu endpoint for your web app.

**Closed** 2018-07-18 15:51 UTC
Labels: discussion

**Comment by skyflyer** [comment] 2018-11-30 19:35
Hi guys! I know this issue is closed, but I believe I might be hitting the same issue on AppService. I have not enabled any extensions specifically and that's what azure portal says. On the Kudu webpage though, I see a webjob: `ApplicationInsightsProfiler3`

I also see `TRACE` error messages in AppInsights and I have all of my components configured to log to AI via Serilog. The trace message I'm seeing:

```
AI: Server telemetry channel was not initialized. So persistent storage is turned off. You need to call ServerTelemetryChannel.Initialize(). Currently monitoring will continue but if telemetry cannot be sent it will be dropped.
```

And I have configured Serilog like this:
```c#
                        var configuration = new TelemetryConfiguration() {
                            InstrumentationKey = hostingContext.Configuration.GetValue<string>("ApplicationInsights:InstrumentationKey"),
                            TelemetryChannel = new ServerTelemetryChannel() { 
                                DeveloperMode = hostingContext.HostingEnvironment.IsDevelopment()
                            }
                        };
                        loggerConfiguration.WriteTo.ApplicationInsightsEvents(configuration);
```

The log messages from the apps are showing up in AI, so it is working, but I'm not sure if I should instantiate `ServerTelemetryChannel` and call initialize and then pass that into `TelemetryConfiguration`.

I don't know how to check the version of AI extension in Azure AppService (since it says none are installed) and Kudu says the same (none are installed).

**Comment by pharring** [comment] 2018-11-30 19:43
As the message says, you need to call `Initialize` on `ServerTelemetryChannel` before it can be used. i.e.

```C#
    var telemetryChannel = new ServerTelemetryChannel { 
        DeveloperMode = hostingContext.HostingEnvironment.IsDevelopment()
    };

    var configuration = new TelemetryConfiguration {
        InstrumentationKey = hostingContext.Configuration.GetValue<string>("ApplicationInsights:InstrumentationKey"),
        TelemetryChannel = telemetryChannel
    };

    telemetryChannel.Initialize(configuration);
    loggerConfiguration.WriteTo.ApplicationInsightsEvents(configuration);
```

**Comment by skyflyer** [comment] 2018-11-30 22:55
Thanks @pharring!
