### ISSUE TITLE
How to enable Azure.Messaging.ServiceBus traces

### ISSUE THREAD

**Issue by Shishkovskiy** [microsoft/ApplicationInsights-dotnet#2511] opened 2022-01-10 19:23 UTC
Net Core 3.1
Microsoft.ApplicationInsights.AspNetCore Version="2.18.0" 
Azure.Messaging.ServiceBus Version="7.5.0-beta.1" 

As I can see, you support another version of the **Service Bus** :

![image](https://user-images.githubusercontent.com/20126169/148826374-5b5a93ac-8ed0-443c-82e7-29298dc981e5.png)

Anyway, I've tried to configure it something like that, but it hasn't worked for me:

```
            services.ConfigureTelemetryModule<DependencyTrackingTelemetryModule>(
                (dependencyTrackingTelemetryModule, _) =>
                {
                    dependencyTrackingTelemetryModule.IncludeDiagnosticSourceActivities.Add("Azure.Messaging.ServiceBus");
                });

            services.AddApplicationInsightsTelemetry();
```

I haven't got any traces related to my function, where it has been called from. 
I sent the request from my Web API after that message went to the service bus and my function was triggered. 
In **Application Insights -> Performance** I didn't see any details about that request, just saw main traces without dependencies.

What is wrong here? Could you assist with it?

**Comment by Shishkovskiy** [comment] 2022-01-14 16:24
@cijothomas  Could you assist with it?

**Comment by cijothomas** [comment] 2022-01-14 18:29
Duplicate of https://github.com/microsoft/ApplicationInsights-dotnet/issues/2151

**Closed** 2022-01-18 19:04 UTC
Labels: question
