### ISSUE TITLE
When using AI in generic host (HostBuilder) it prevents app shutdown

### ISSUE THREAD

**Issue by skyflyer** [Microsoft/ApplicationInsights-dotnet#1076] opened 2018-11-29 19:43 UTC
I'm using AI logging with Serilog in a console application, with the generic host builder. When I press Ctrl-C, the application lifecycle detects the event and shuts down the app, but the process stays alive. The process does end when issuing a `kill` command though.

I'm developing on a Mac, and the host builder config to reproduce this problems follows:

```c#
        static async Task MainAsync(string[] args)
        {
            var host = new HostBuilder()
                .UseConsoleLifetime()
                .UseContentRoot(Directory.GetCurrentDirectory())
                .ConfigureHostConfiguration(conf => {
                    conf.SetBasePath(Directory.GetCurrentDirectory());
                })
                .ConfigureAppConfiguration((hostContext, configHost) => {
                    configHost.SetBasePath(Directory.GetCurrentDirectory());
                    configHost.AddJsonFile("appsettings.json", optional: false);
                    configHost.AddJsonFile($"appsettings.{hostContext.HostingEnvironment.EnvironmentName}.json", optional: true);
                    configHost.AddJsonFile("appsettings.local.json", optional: true);
                    configHost.AddEnvironmentVariables();
                    configHost.AddCommandLine(args);
                })
                .UseSerilog((hostingContext, loggerConfiguration) => {
                    loggerConfiguration
                        .Enrich.WithProperty("ApplicationName", "Melbourne.Frontend")
                        .MinimumLevel.Debug()
                        .MinimumLevel.Override("Microsoft", new LoggingLevelSwitch{MinimumLevel=LogEventLevel.Warning})
                        .MinimumLevel.Override("Microsoft.AspNetCore.Hosting.Internal.WebHost", new LoggingLevelSwitch{MinimumLevel=LogEventLevel.Information})
                        .WriteTo
                            .Console(
                                outputTemplate: "{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{SourceContext}] [{Level:u30}] {Message:l}{NewLine}{Exception}"
                            );

                    if (!hostingContext.HostingEnvironment.IsDevelopment()) {
                        Console.WriteLine($"Configuring ApplicationInsights logging");
                        var configuration = new TelemetryConfiguration() {
                            InstrumentationKey = hostingContext.Configuration.GetValue<string>("ApplicationInsights:InstrumentationKey"),
                            TelemetryChannel = new ServerTelemetryChannel() { 
                                DeveloperMode = hostingContext.HostingEnvironment.IsDevelopment()
                            }
                        };
                        loggerConfiguration.WriteTo.ApplicationInsightsEvents(configuration);
                    }
                })
                .Build();

            await host.RunAsync();
        }
```

Perhaps I'm using it wrong or perhaps it is a Serilog issue, but I suspect it is a `ServerTelemetryChannel` issue. If this is a wrong repository, please point me to the right one.

**Comment by rossdargan** [comment] 2019-02-03 20:59
I had to remove the Microsoft.ApplicationInsights.Extensibility.AutocollectedMetricsExtractor processor to allow the app to exit without issue.

**Comment by Dmitry-Matveev** [comment] 2019-02-05 00:11
@ig-sinicyn , @rossdargan's workaround should help. #1081 is addressing this issue.
The part about Server Telemetry Channel is still unknown, though. @cijothomas to take a look.

**Comment by ig-sinicyn** [comment] 2019-02-05 09:36
@Dmitry-Matveev
> @rossdargan's workaround should help.

I'm new with telemetry configuration, can you help me with removing the `AutocollectedMetricsExtractor` ?

Thanks!

**Comment by nhart12** [comment] 2019-02-05 17:00
> @Dmitry-Matveev
> 
> > @rossdargan's workaround should help.
> 
> I'm new with telemetry configuration, can you help me with removing the `AutocollectedMetricsExtractor` ?
> 
> Thanks!
Should just need to disable it in the ApplicationInsightsServiceOptions
.AddApplicationInsightsTelemetry( opt =>
                {
                    opt.InstrumentationKey = Configuration["ApplicationInsights:InstrumentationKey"];
                    opt.AddAutoCollectedMetricExtractor = false;
                })

**Comment by cijothomas** [comment] 2019-02-05 17:03
Since ServerTelemetryChannel/InMemoryChannel does not create a new Thread() like the new metric aggregator, i am assuming for now that the issue is mitigated by removing AutoCollectedMetricExtractor, and will be fixed in next release. 
Will re-visit if issue persists even after removing AutoCollectedMetricExtractor

**Comment by cijothomas** [comment] 2019-02-05 17:04
Just realized that the original issue by @skyflyer still need to be investigated as it was occuring with older version of MetricExtractor which did not spin up new Thread().

**Comment by ig-sinicyn** [comment] 2019-02-05 20:15
@nhart12 
Thanks for help! Is there something like this for console apps? No web, no DI, etc.

I'm using AI to collect custom telemetry from windows service process. I've added nuget package, set the AI key and did not change default configuration at all, [simple repro](https://github.com/Microsoft/ApplicationInsights-Home/files/2816168/ReproAppInsights.zip). Under debugger there is no AutoCollectedMetricExtractor in AI processor/telemetry sinks.

**Comment by cijothomas** [comment] 2019-02-05 20:41
@ig-sinicyn From the repro you shared, it looks .like you are using the new aggregating metric api. This would be suffering from the same problem as AutoCollectedMetricExtractor. Your only workaround them would be to downgrade to beta2. Can you try that ?

**Comment by ig-sinicyn** [comment] 2019-02-06 06:34
Nope:( 
We've tried that and our web and service app suffered from massive threadpool / memory leaks (up to 9000 threads/1 gb mem per day). Currently, as a workaround, I'm killing the process using exit watchdog.

**Comment by cijothomas** [comment] 2019-02-06 07:18
@ig-sinicyn what caused threapool/memory leak?

**Comment by ig-sinicyn** [comment] 2019-02-07 06:52
@cijothomas 
We did not investigate leaks deeply, as we had to fix them ASAP but symptoms were much like a combo of #1026 and #895.

**Comment by ig-sinicyn** [comment] 2019-03-07 08:25
@cijothomas 
Just to make you know, the 2.9.0 fixed issue with the app shutdown for us.

**Closed** 2019-03-11 18:45 UTC
Labels: bug, channel, metrics
