### ISSUE TITLE
.Net Standard 2.0 Azure Function error referencing Microsoft.ApplicationInsights 2.7.2

### ISSUE THREAD

**Issue by ShawnCholeva** [Microsoft/ApplicationInsights-dotnet#921] opened 2018-09-20 15:43 UTC
If you are reporting bug/issue, please provide detailed Repro instructions.

## Repro Steps
1.  Create an Azure Function Project in Visual Studio 2017 as v2 (.NET Core) with a Timer Trigger set to occur ever 1 minute instead of 5.
2. Add the nuget package Microsoft.ApplicationInsights(2.7.2)
3.  Create a new TelemetryClient instance in the Run method such as:
```var telemetryClient = new TelemetryClient();```
4.  Add the using statement for Microsoft.ApplicationInsights
5.  Press play and see the follow exception displayed in the console.

##  Actual Behavior

```[9/20/2018 3:35:03 PM] Executing 'Function1' (Reason='Timer fired at 2018-09-20T10:35:03.9231283-05:00', Id=f4125c72-582e-436a-8a2e-27607e490005)```
```[9/20/2018 3:35:04 PM] Executed 'Function1' (Failed, Id=f4125c72-582e-436a-8a2e-27607e490005)```
```[9/20/2018 3:35:04 PM] System.Private.CoreLib: Exception while executing function: Function1. FunctionApp1: Could not load file or assembly 'Microsoft.ApplicationInsights, Version=2.7.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621). System.Private.CoreLib: Could not load file or assembly 'Microsoft.ApplicationInsights, Version=2.7.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.```

## Expected Behavior

A function would run successfully and a new instance of TelemetryClient could be created.

## Version Info 
SDK Version : Microsoft.NET.Sdk.Functions (1.0.21)
.NET Version :	.Net	Standard 2.0					
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) :
OS : Windows 10
Hosting Info (IIS/Azure WebApps/ etc) : Locally ran Azure Function

**Comment by Dmitry-Matveev** [comment] 2018-09-25 01:34
@brettsam, @lmolkova are you aware of such issue in AF with AI SDK 2.7.2? Let's investigate in 2.8 milestone to check if it's a regression. If not - I'd suggest fixing in 2.9 milestone.

**Comment by lmolkova** [comment] 2018-10-02 00:46
@ShawnCholeva 
You could only use AppInsights 2.5.0 with function v1: https://github.com/Azure/azure-webjobs-sdk/issues/1695. This is by design.

Please consider updating to Function v2.

I'm closing the issue. Feel free to reopen if needed.

**Closed by lmolkova** 2018-10-02 00:46 UTC
Labels: bug
