### ISSUE TITLE
Azure Service bus Receive dependency is not correlated correctly

### ISSUE THREAD

**Issue by Vlad-Stryapko** [Microsoft/ApplicationInsights-dotnet#1033] opened 2018-12-21 18:30 UTC
Hi, 

I was testing AI with Azure Service Bus and noticed pretty weird behaviour. 

Repro:

1. Set up a .NET Core Console app with the latest AI, AI Dependency Collector and Azure Service Bus packages. 
2. Publish a message to SB.

```
TelemetryConfiguration configuration = TelemetryConfiguration.Active;
configuration.InstrumentationKey = "key";
using (InitializeDependencyTracking(configuration))
{
    var telemetryClient = new TelemetryClient();
    var client = new QueueClient(ConnectionToSb, EntityName);
    using (var operation = telemetryClient.StartOperation<Microsoft.ApplicationInsights.DataContracts.RequestTelemetry>("PublishMessageToSb"))
    {
        var msg = Encoding.UTF8.GetBytes("test");
        telemetryClient.TrackEvent("Before publishing");
        client.SendAsync(new Message(msg)).Wait();
        telemetryClient.TrackEvent("Published!");
    }
    telemetryClient.TrackEvent("Finishing the app");
    telemetryClient.Flush();
}
```

3. Consume the message

```
TelemetryConfiguration configuration = TelemetryConfiguration.Active;
configuration.InstrumentationKey = "key";
using (InitializeDependencyTracking(configuration))
{
    var telemetryClient = new TelemetryClient();
    var client = new QueueClient(ConnectionToSb, EntityName);
    var messageHandlerOptions = new MessageHandlerOptions(async arg => await Task.CompletedTask)
    {
        MaxConcurrentCalls = 1,
        AutoComplete = true,
        MaxAutoRenewDuration = TimeSpan.FromMinutes(5)
    };
    client.RegisterMessageHandler(async (message, token) =>
    {
        telemetryClient.TrackEvent("Handling message");
        await Task.Delay(3 * 1000);
        telemetryClient.TrackEvent("Handled the message");
    }, messageHandlerOptions);
    telemetryClient.TrackEvent("Finishing the app");
    telemetryClient.Flush();
}
```

4. Check AI logs to see the correlation of events.

Expected: each event is correlated and there is a sequence of Send, Receive, Complete Service Bus operations.

Actual: Send and Complete operations are correlated, but the Receive operation stands on its own and has unique Operation Id which is not shared by any other event, dependency or request whatsoever.

Here's how it looks when I query AI by Operation Id:

![screenshot_1](https://user-images.githubusercontent.com/22256471/50357555-ff4fdf00-055e-11e9-81c3-dbe22a28a1dd.png)

**Comment by lmolkova** [comment] 2018-12-21 23:20
this is expected for now. When receive operation starts, there is no way of knowing which message(s) it will receive and which operation ids will be in there. Note there may be more than one.

See more on this here: 

https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-end-to-end-tracing#logging-additional-properties


At some point, we will fix it, but now it's by design.

**Closed** 2018-12-21 23:20 UTC

**Comment by Vlad-Stryapko** [comment] 2018-12-21 23:37
Wonderful, thanks for clarification. Not a major issue for sure, just wanted to double check.
