### ISSUE TITLE
[ASPNET Core] Memory Usage / GC Thrashing

### ISSUE THREAD

**Issue by ctolkien** [microsoft/ApplicationInsights-dotnet#1270] opened 2019-10-24 23:50 UTC
Fairly basic ASPNET Core Application, 1 minute after booting sitting there idling, there is a huge amount of GC thrashing and the memory is nearly peaking at 600mb:
![image](https://user-images.githubusercontent.com/515955/67533270-129a8080-f715-11e9-8941-b247cfd20b85.png)

Compared with if AI is _not_ enabled, no GC thrashing, memory usage at 150mb:
![image](https://user-images.githubusercontent.com/515955/67533280-1f1ed900-f715-11e9-83ba-16feead7191d.png)

Only difference is:
`services.AddApplicationInsightsTelemetry();`

**Comment by cijothomas** [comment] 2019-10-29 00:20
Thanks for reporting the issue with repros. Yes this is easy to repro, and reproes in all sdk versions, and in both .net core and .net framework apps. This is not a bug inside the sdk itself, but from the perfcounter library. Trying to find owners to get this tracked/fixed appropriately.

**Comment by ctolkien** [comment] 2019-11-04 21:26
Hi @cijothomas  - I recognise this isn't an issue in AppInsights directly, but net result is this is slowing our devs down, so we're yanking AI out.

**Comment by jeffadavidson** [comment] 2020-02-07 17:27
@cijothomas do you any update on this?

**Comment by Dmitry-Matveev** [comment] 2020-02-10 22:51
@cijothomas , assigned to you to check on the status of your conversation with the code owners.

**Comment by evilpilaf** [comment] 2020-03-11 11:06
This looks exactly like the issue I'm facing and describe here
https://github.com/microsoft/ApplicationInsights-dotnet/issues/1678#issuecomment-597498892
Is there any ETA on it?

**Comment by cijothomas** [comment] 2020-03-11 16:48
@evilpilaf This issue is arising from PerformanceCounter. 
The other issue and the screenshot share appears from DiagnosticSource related. They are separate problems.

**Comment by SidShetye** [comment] 2020-03-17 22:29
Seeing the same on .NET Core 3.1 and `Microsoft.ApplicationInsights.AspNetCore` v2.13.1.

![image](https://user-images.githubusercontent.com/2595088/76907366-46f90f80-6863-11ea-9f2e-6291dc297c94.png)

If you don't need the AppInsight collected metrics you can disable that module in your `startup.cs`'s `ConfigureServices(IServiceCollection services)` 

```
services.AddApplicationInsightsTelemetry(opt => {
	opt.EnablePerformanceCounterCollectionModule = false;
});
```

Obviously this is a work-around till the real issue is resolved but it works for us since we're gathering similar metrics at our hosting layer.

**Comment by cijothomas** [comment] 2020-03-31 22:37
This is fixed https://github.com/microsoft/ApplicationInsights-dotnet/issues/1694 from 2.14.0-beta1 onwards.

**Closed by cijothomas** 2020-03-31 22:37 UTC

**Comment by ojpbay** [comment] 2021-03-15 11:33
@cijothomas - can you please confirm the exact version of the framework this fix went into. We have current production apps that suffer from similar issues to those mentioned by @evilpilaf  and they are on runtime 3.1.112 (build agents are on 3.1.404). 

![image](https://user-images.githubusercontent.com/1391064/111147287-37013200-8582-11eb-88ff-9ff6693c058a.png)
