### ISSUE TITLE
How to make ApplicationInsights working with legacy ASP.NET 

### ISSUE THREAD

**Issue by yahorsi** [microsoft/ApplicationInsights-dotnet#1931] opened 2020-06-22 19:10 UTC
Hi guys,

I'm desperately spending my time on the attempts to make AI working with ASP.NET legacy app.
I'm so doomed that I even created the app from the scratch, add AI and it still does not work.
The problem is that I do not see any events (no availability data, no server requests, no server response time, no any events, just nothing) in my AI Azure resource, but I see them when debugging locally, in the debug output, or even in the AI VS plugin.

So, I have full repo:
1. The code (https://github.com/yahorsi/AiWithLove) was made using 2 simple steps:
    a) Create ASP.NET App
    b) Add Application Insight using VS
 
2. Code is deployed using VS to the http://aiwithlove.azurewebsites.net/
3. Subscription 3528c48b-d4d8-4051-b03c-c919e7d70ae7
4. Instrumentation Key 3d88dc8f-3123-4f78-b4a3-0ce29c1eabda
5. App Service/Ai AiWithLove

I have no ideas what's going on

Thanks for any ideas.

**Comment by cijothomas** [comment] 2020-06-22 19:29
What do you see in local debug sessions? can you paste a screenshot of the same?

**Comment by cijothomas** [comment] 2020-06-22 19:34
I think this is a bug in Visual Studio. Can you put the ikey in your ai.config file (https://github.com/yahorsi/AiWithLove/blob/master/ApplicationInsights.config)? 
The Visual Studio Add Application Insights may be broken.

**Comment by yahorsi** [comment] 2020-06-22 19:59
I am using 16.6.1

In the Output Debug I see AI events:
![image](https://user-images.githubusercontent.com/9819679/85328762-f506fc00-b4d9-11ea-9851-61d57bdce63a.png)


I'm also able to see them in the AI plugin:
![image](https://user-images.githubusercontent.com/9819679/85328790-03edae80-b4da-11ea-92ca-4e9d08f818ff.png)


I have explicitly set the environment variables APPINSIGHTS_INSTRUMENTATIONKEY and APPLICATIONINSIGHTS_CONNECTION_STRING and yes I have restarted VS and app to make sure variables takes effect.


I would love to add it to the config but there is no any sample. It's not even shown how to set it in the "main" ApplicationInsight.config article here:
https://docs.microsoft.com/en-us/azure/azure-monitor/app/configuration-with-applicationinsights-config#instrumentationkey

So, I add it in the code following way:
![image](https://user-images.githubusercontent.com/9819679/85329790-dc97e100-b4db-11ea-9167-483319d8ed0d.png)


No luck so far, still no events in the AI Azure resource are available

**Comment by cijothomas** [comment] 2020-06-22 20:01
So not an ikey issue. Can you check Fiddler to see if application insights ingestion endpoints are reachable and are responding ?

**Comment by yahorsi** [comment] 2020-06-22 20:12
I gave up finding what's the issue ((
Someone just need to try to create a legacy ASP.NET app, just create, add AI, and try making it working.

My app is running in Azure and locally, with no events from both sites.
A bit strange as I see both sites (local and Azure) in the live metrics.

**Comment by cijothomas** [comment] 2020-06-22 20:18
Since you see data locally in Visual Studio, there is nothing wrong with SDK, and the screenshot shows it even has correct instrumentation key.
Either the machine has network issues to reach Application Insights backend, or data is rejected for this particular ikey due to throttling or quota or something else.. (most likely case as LiveMetric works)

Closing as no action item for the SDK.

**Closed by cijothomas** 2020-06-22 20:18 UTC
Labels: question

**Comment by yahorsi** [comment] 2020-06-22 20:20
What I am supposed to do next? I have created 2 new App Service-es, with 2 different AI instances. No any traffic, no data, no quotas. Where to dig?

**Comment by yahorsi** [comment] 2020-06-22 20:23
@pharring May I ask you to help, this does not seem right.

**Comment by cijothomas** [comment] 2020-06-22 23:28
> What I am supposed to do next? I have created 2 new App Service-es, with 2 different AI instances. No any traffic, no data, no quotas. Where to dig?

I already gave my suggestion on how to continue the investigation. Feel free to follow that, or you may open Azure support case.

This repo is for the SDK issues, and from what you shared, there is no issue with SDK or its configuration.

**Comment by yahorsi** [comment] 2020-06-23 21:06
Seems you're right, custom events and metrics are available only in the Live Metrics. Created support case. Thanks

**Comment by yahorsi** [comment] 2020-06-27 09:26
Just an update:
The problem was in the Azure Region we were using.
We've created Application Insights resource in the Germany West Central data canter, the data center was available for choice in the Azure Portal but it turned out that Application Insights is not available there.
At least partially, Live Metrics was working just fine but events were not persisted.

**Comment by zakimaksyutov** [comment] 2020-12-09 19:56
@yahorsi, you're right. I think this was caused by a bug that a few regions were accidently opened before all work completed. Germany West Central started supporting Application Insights in Preview mode in October 2020.

Here is the link which tracks its status:

https://azure.microsoft.com/en-us/global-infrastructure/services/?products=monitor&regions=us-central,us-east,us-east-2,us-north-central,us-south-central,us-west-central,us-west,us-west-2,europe-north,europe-west,germany-non-regional,germany-central,germany-north,germany-northeast,germany-west-central
