### ISSUE TITLE
Global Properties do not show up for customMetrics

### ISSUE THREAD

**Issue by rennerg** [microsoft/ApplicationInsights-dotnet#1228] opened 2019-10-01 19:04 UTC
Hi,

I'm having trouble getting global properties to show up in AI when tracking custom metrics. The code is pasted below. Using the same pattern below for tracking custom events, I can get global properties to show up for custom events just fine, however AI seems to discard them for metrics.

## Code / Steps to Repro
```c#
public static void TrackMetric(int metricValue)
{
    var config = new TelemetryConfiguration
    {
          InstrumentationKey = _instrumentationKey,
          TelemetryChannel = new ServerTelemetryChannel(),
          DisableTelemetry = false
    };
    config.TelemetryChannel.DeveloperMode = Debugger.IsAttached;
    config.TelemetryProcessorChainBuilder.UseSampling(100); 

    var client = new TelemetryClient(config);
    client.Context.Session.Id = Guid.NewGuid();
    client.Context.GlobalProperties.Add("globalPropertyName1", "globalPropertyValue1");
    client.Context.GlobalProperties.Add("globalPropertyName2", "globalPropertyValue2");
    client.Context.GlobalProperties.Add("globalPropertyName3", "globalPropertyValue3");

    var metricId = new MetricIdentifier("defaultNamespace", 
                                        "metricName",
                                        "localPropertyNameA",
                                        "localPropertyNameB",
                                        "localPropertyNameC");
    var metric = client.GetMetric(metricId);
    metric.TrackValue(metricValue,
                      "localPropertyValueA",
                      "localPropertyValueB",
                      "localPropertyValueC");
}
```

##  Actual Behavior
In our AI 'Logs (Analytics)' on Azure when I query `customMetrics`, I see the metric items as expected, however the global properties I'm setting do not show up in customDimensions like they do for `customEvents`. The item-level properties do show up as expected. 

## Expected Behavior
Based on how custom events work with global props, I would expect custom metrics to contain the global props as well. Is there a difference in how global properties are handled between customMetrics and customEvents? 

Thanks!

## Version Info 
SDK Version : 2.10.0.0
.NET Version :	.NET Framework 4.5.2 						
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) : Visual Studio
OS : Windows 10
Hosting Info (IIS/Azure WebApps/ etc) : WPF & WCF Windows processes

**Comment by mrbullwinkle** [comment] 2019-10-01 19:30
Have you tried going to **Usage and estimated costs** > **Custom Metrics preview** > **Enable alerting on custom metric dimensions**? ![metrics](https://raw.githubusercontent.com/mrbullwinkle/GitHub_Issues/master/1128/dimensional-metrics.png)

My understanding is if this setting is not enabled we strip out all dimensional data and metrics are sent to the custom metrics store flattened.

**Comment by rennerg** [comment] 2019-10-01 19:52
Thanks @mrbullwinkle. I've enabled *Enable alerting on custom metric dimensions* and sent some metrics through but it doesn't seem to fix the issue. 

I'm not seeing all dimensional data being removed from `customMetrics`, only the global properties set via `TelemetryClient.Context.GlobalProperties`. My item-level properties/dimensions are there Log Analytics in the `customDimensions` when *Enable alerting on custom metric dimensions* is both enabled and disabled.

**Comment by cijothomas** [comment] 2019-10-01 20:30
@rennerg it looks like a bug that aggregating metric api (GetMetric().Track()) is not respecting the GlobalProperties set of the TelemetryClient. Will fix this.

**Comment by cijothomas** [comment] 2019-10-01 20:32
@rennerg btw - on a separate note - the sample code you shared is not recommended for any production scenarios. You should just create telemetryconfiguration/channel once and reuse it, instead of creating new ones. 

You can try the new SDK and doc: https://docs.microsoft.com/en-us/azure/azure-monitor/app/worker-service#net-corenet-framework-console-application

**Comment by cijothomas** [comment] 2019-10-01 20:33
> Have you tried going to **Usage and estimated costs** > **Custom Metrics preview** > **Enable alerting on custom metric dimensions**? ![metrics](https://raw.githubusercontent.com/mrbullwinkle/GitHub_Issues/master/1128/dimensional-metrics.png)
> 
> My understanding is if this setting is not enabled we strip out all dimensional data and metrics are sent to the custom metrics store flattened.
> 
> (But I thought this behavior would only impact custom metrics from the perspective of the Metrics/Metrics explorer interface which rely on the metrics store and not from within the Analytics experience which relies on the Log Analytics style partition so you may be experiencing a different issue than the one my suggestion would resolve since you are seeing this behavior when querying in Analytics.)

@mrbullwinkle you are right - that only impacts the Metric Explorer behaviour, not impact on LogAnalytics.

**Comment by rennerg** [comment] 2019-10-02 14:39
@cijothomas thanks for the side note. We aren't actually creating the TelemetryClient for each call, that's just a simplified example to demonstrate the issue. 

Thanks in advance for the fix :)

**Comment by rennerg** [comment] 2019-10-02 14:58
Additionally, I also don't see the `TelemetryClient.Context.Session.Id` or `TelemetryClient.Context.Device.OperatingSystem` that I set explicitly showing up in the `customMetrics` items either. For `customEvents`, they shows up as `session_Id` and `client_OS`, respectively, in each of the event items but not for the metric items. 

I'm attempting to set `TelemetryClient.Context.Device.Id` which I'm not sure is showing up for both `customMetrics` or `customEvents`. In Log Analytics I see a `cloud_RoleInstance` for each item type that has the value of my host name but I don't know if that is set from the environment or set by me explicitly.

**Comment by cijothomas** [comment] 2019-10-02 16:01
Yes, the whole Getmetric() api is NOT using the telemetryclient's context.
Context.DeviceId is missing due to this bug- https://github.com/microsoft/ApplicationInsights-Home/issues/394

cloudRoleInstance is by default populated with machine name.

**Comment by rennerg** [comment] 2019-10-02 16:03
@cijothomas gotcha thanks.

**Comment by Liversage** [comment] 2019-10-15 14:00
I'm having an issue that might be related. I'm sending custom metrics using a `MetricIdentifier`. These are scoped to a namespace so I use "generic" names for my custom metrics like _durationMilliseconds_.

In the Azure Portal I can graph the data in the _Metrics_ blade where I can select my custom metric namespace and the named metric and see a graph. Unfortunately, I'm unable to filter or split the data based on my custom dimensions.

To work around this I can access the "raw" metrics by querying `customMetrics` in the _Logs (Analytics)_ blade where my custom dimensions are included in `customDimensions` value and build a graph from these data. However, to my surprise, `customMetrics` does not include the metrics namespace making it impossible to narrow the query to a specific namespace. And with metric names like _durationMilliseconds_ used in several namespaces I'm unable to query on a _durationMilliseconds_ in a specific namespace. Shouldn't that be possible?

@rennerg, in your repro is the namespace (in your case _defaultNamespace_) included in `customMetrics`?

**Comment by rennerg** [comment] 2019-10-15 18:13
@Liversage No, the namespace is not included in either the customMetrics or customEvents items. I'm not sure I would want it to be as that's just additional space per data item we'd have to pay for. IMHO namespaces should know about the data items sent to them, but data items should not necessarily know about the namespaces. 

Have you considered using a single namespace and switching from "generic" metric names to "non-generic" names?

**Comment by cijothomas** [comment] 2019-10-15 19:07
Just to give an update: it is by design that telemetryclient's context is not used in the metrics produced by the GetMetric().TrackValue(). The metrics can be aggregated in the scope of telemetryClient or telemetryConfiguration. This is a documentation problem, which should have explained how to add context properly. Unfortunately that doc don't exist. 

There is an issue opened in docs repo to have a new docs for metrics api alone. I'll post an update here when that doc is ready.

**Comment by rennerg** [comment] 2019-10-15 19:15
@cijothomas do you know if it is or will be possible to do what I'm trying to do in the above code example? Because the number of custom dimensions is limited in GetMetric().TrackValue() to at most 10, I cannot get all of the contextual custom metrics I need, as far as I can tell.

**Comment by cijothomas** [comment] 2019-10-15 19:30
The max dimension of 10 - is a limit of back end and there are no plans to increase it. So you'll be able to have utmost 10 dimensions. (even if you add existing things like context.operation.name they count as 1 to the overall 10)

**Comment by cijothomas** [comment] 2019-10-15 20:48
@Liversage 
"Unfortunately, I'm unable to filter or split the data based on my custom dimensions."

This is opt-in.  You need to enable it explicitly:
https://docs.microsoft.com/en-us/azure/azure-monitor/app/pre-aggregated-metrics-log-metrics#custom-metrics-dimensions-and-pre-aggregation

Some time in future, the custom metric gets billed separately, hence its opt-in.

**Comment by cijothomas** [comment] 2019-11-01 01:41
tracking docs issue here: https://github.com/MicrosoftDocs/azure-docs/issues/40231
closing this, as I believe the questions are answered. Please reopen if not.

**Closed by cijothomas** 2019-11-01 01:41 UTC
Labels: metrics
