### ISSUE TITLE
A Metric Extractor detected a telemetry item with SamplingPercentage < 100

### ISSUE THREAD

**Issue by GMillerVarian** [microsoft/ApplicationInsights-dotnet#2793] opened 2023-06-26 15:51 UTC
* List of [NuGet packages](https://github.com/microsoft/ApplicationInsights-dotnet#nuget-packages) and version that you are using:
Microsoft.ApplicationInsights.AspNetCore 2.21.0 (also confirmed with latest 2.22.0-beta3)

* Runtime version (e.g. net461, net48, netcoreapp2.1, netcoreapp3.1, etc. You can find this information from the `*.csproj` file):
net6.0 (.NET 6.0.19)

* Hosting environment (e.g. Azure Web App, App Service on Linux, Windows, Ubuntu, etc.):
Issue occurs both in our deployed Ubuntu environments as well as locally under Windows

### Describe the bug

When [configuring fixed-rate sampling for ASP.NET Core applications](https://learn.microsoft.com/en-us/azure/azure-monitor/app/sampling#configuring-fixed-rate-sampling-for-aspnet-core-applications) we see the following trace log appear multiple times in Application Insights:

"AI: A Metric Extractor detected a telemetry item with SamplingPercentage < 100. Metrics Extractors should be used before Sampling Processors or any other Telemetry Processors that might filter out Telemetry Items. Otherwise, extracted metrics may be incorrect."

### To Reproduce

We are calling the following from ConfigureServices in startup.cs:

```cs
    public static IServiceCollection AddApplicationInsights(this IServiceCollection services)
    {
        services.Configure<TelemetryConfiguration>(telemetryConfiguration =>
        {
            var builder = telemetryConfiguration.DefaultTelemetrySink.TelemetryProcessorChainBuilder;
            builder.UseSampling(1, excludedTypes: "Event;Exception;Trace");
        });

        var options = new ApplicationInsightsServiceOptions
        {
            ConnectionString = "conection string",
            EnableAdaptiveSampling = false
        };

        services.AddApplicationInsightsTelemetry(options);

        return services;
    }
```

If we change the order, and call Configure() after calling AddApplicationInsightsTelemetry() then the fixed rate sampling of 1% that we specified does not take effect, we see 100% of requests logged.

**Comment by msscars** [comment] 2023-10-19 09:59
same here. Any updates?

**Comment by cijothomas** [comment] 2023-10-19 17:20
The internal log is doing the right thing - the MetricExtractor is expected to extract metrics pre-sampling. So, if it is added after the sampling processor, it'll give inaccurate results, so its doing the right thing by warning!

**Comment by GMillerVarian** [comment] 2023-10-19 17:27
Can you please explain how to implement this correctly then? 

As mentioned above:

> If we change the order, and call Configure() after calling AddApplicationInsightsTelemetry() then the fixed rate sampling of 1% that we specified does not take effect, we see 100% of requests logged.

**Comment by cijothomas** [comment] 2023-10-19 17:34
Unfortunately, I do not have the bandwidth to investigate and provide a correct way. I simply removed the "bug" tag, as this is not a bug. If the doc is missing something or showing incorrect thing (likely to be the case, it seems), I agree the docs needs to be fixed. (perhaps better is to open issue against the doc.)

**Comment by cijothomas** [comment] 2023-10-20 14:37
Please open a separate issue for that. The original issue posted is not a bug. But if sampling does not work as expected, then it is a bug, but I'd suggest to open it separately.

**Comment by cijothomas** [comment] 2023-10-20 16:30
Closing as this is not a bug and working as expecting. The sampling-not-working is resolved in the linked issue.

**Closed by cijothomas** 2023-10-20 16:30 UTC
