### ISSUE TITLE
Ability to change the `_MS.AggregationIntervalMs` interval time for preaggregation

### ISSUE THREAD

**Issue by StevenBucher98** [microsoft/ApplicationInsights-dotnet#2563] opened 2022-03-24 22:33 UTC
* List of [NuGet packages](https://github.com/microsoft/ApplicationInsights-dotnet#nuget-packages) and version that you are using: 2.15.0
* Runtime version (e.g. net461, net48, netcoreapp2.1, netcoreapp3.1, etc. You can find this information from the `*.csproj` file): 2.20.0
* Hosting environment (e.g. Azure Web App, App Service on Linux, Windows, Ubuntu, etc.): Windows, Linux, Mac, anything that runs PowerShell 7.x

**What are you trying to achieve?**
We are having too much data being sent to our App Insights ingestion point and are looking at ways to reduce our `customMetrics` events since it is the largest segment of data. One option we are exploring is increasing the interval of which preaggregation events are sent out, the `_MS.AggregationIntervalMs` value within our customMetrics. Is this possible? How might we lengthen the time from 60000ms to something greater? 

**What have you tried so far?**
We have explored the option of sampling but have discovered that `customMetrics` events are ignored with ingestion sampling so is unhelpful.

**Comment by cijothomas** [comment] 2022-03-24 23:28
Aggregation Interval of 1 minute - it is not changeable as it is a backend limitation as well.
Sampling is not applied to Metrics, by design.

How is the `customMetrics` generated in your case? Is it automatically emitted by the SDK? Or you are emitting it yourself? Its a bit suprising that metrics take up the majority of the data...

**Comment by StevenBucher98** [comment] 2022-03-25 02:40
@cijothomas we have a unique case where we are emitting `customMetrics` ourselves to track telemetry for PowerShell sessions, things like module loads, application types, remote sessions and so on. Since PowerShell usage grows, session data grows with it and is causing us to go over our ingestion limits. Aggregation works _ok_ for us but since we have very ganular data there is often times of a particular session having many many `customMetric` events that take up a lot of ingestion space.

**Comment by cijothomas** [comment] 2022-03-25 13:48
Okay. I wanted to rule out an old issue in the SDK where it was collecting EventCounters by default (leading to increased metrics volume), and we turned that feature off by default.

**Comment by StevenBucher98** [comment] 2022-03-25 16:07
Yes we use preaggregation, here is the implementation of the SDK [here](https://github.com/PowerShell/PowerShell/blob/ee6bc9527c2596f048088fa7b396d2664a11ad08/src/System.Management.Automation/utils/Telemetry.cs#L629-L665). As far as I know we do not enable multi demensional metrics, does this help reduce total ingestion cost? Our main problem is that we can implement a code change to reduce our telemetry sent but it would not propogate immediately since we would have to do another release of PowerShell

**Comment by cijothomas** [comment] 2022-03-25 16:10
> As far as I know we do not enable multi demensional metrics, does this help reduce total ingestion cost?

No. I was warning it will increase.

**Comment by cijothomas** [comment] 2022-04-06 02:10
Closing as original question is answered.

**Closed by cijothomas** 2022-04-06 02:10 UTC
Labels: question
