### ISSUE TITLE
[Metrics] MetricTelemetry stats don't appear

### ISSUE THREAD

**Issue by breyed** [microsoft/ApplicationInsights-dotnet#412] opened 2017-01-20 17:38 UTC
The statistics properties of `MetricTelemetry` don't show up in the Application Insights events. Complicating matters is that the documentation related to `MetricTelemetry` is a mess. Let's walk through the issues.

Problem 1: Pressing F1 on `MetricTelemetry` gives a useless result.

Problem 2: Googling "MetricTelemetry" gives two top results, one on [MSDN](https://msdn.microsoft.com/en-us/library/microsoft.applicationinsights.contracts.metrictelemetry.aspx) and one on [docs](https://docs.microsoft.com/en-us/dotnet/api/microsoft.applicationinsights.datacontracts.metrictelemetry), neither of which make clear what code they apply to or provide a hint about where other relevant documentation might live. In this case, neither of the online docs match the actual type in the NuGet package: the MSDN version doesn't have nullable types, and the "docs" version has an extra `Sum` property.

Problem 3: The IntelliSense docs on `MetricTelemetry` don't say what to do with `Value` when using statistics. Presumably, it should be the mean, but it would be nice if the intent were documented.

Problem 4: There's no support for calculating the statistical properties, or if there are, the IntelliSense or other docs in `MetricTelemetry` don't link to it, so it's not discoverable.

Problem 5: Even if you calculate the statistics, they don't show up when you view the metric in Application Insights. Only `Value` is displayed.

--

Here's the code I used to generate the statistics. If a helper like this isn't already in the SDK, it would be good to add it and mention it in the `MetricTelemetry` docs.

	public static class TelemetryExtensions
	{
		/// <summary>
		/// Sets the count, min, max, average, and standard deviation of the metric based on a sequence of values. The average is stored in <see cref="MetricTelemetry.Value"/>.
		/// </summary>
		/// <remarks>If the count is zero, only <see cref="MetricTelemetry.Count"/> is set.</remarks>
		public static void SetStatistics(this MetricTelemetry telemetry, IEnumerable<double> values)
		{
			int n = 0;
			double min = double.MaxValue, max = double.MinValue, mean = 0, sum = 0;
			foreach (double value in values) {
				if (value < min) min = value;
				if (value > max) max = value;
				double delta = value - mean;
				mean += delta / ++n;
				sum += delta * (value - mean);
			}

			telemetry.Count = n;
			if (n > 0) {
				telemetry.Min = min;
				telemetry.Max = max;
				telemetry.Value = mean;
				telemetry.StandardDeviation = Math.Sqrt(sum / n);
			}
		}
	}

**Comment by SergeyKanzhelev** [comment] 2017-03-30 18:34
cc: @macrogreg

**Comment by macrogreg** [comment] 2017-04-05 18:08
This looks to me like 3 separate issues:
- Improve docs on TrackMetric
- Feature requests related to metrics UI.
- Feature request for something like the MetricManager

None of it is blocking for 2.4-beta1, correct?

**Comment by breyed** [comment] 2017-04-05 18:58
I think there are 5 separate issues. My guess is that they should be reported to various places, although I don't know where. I'll elaborate:

> Problem 1: Pressing F1 on `MetricTelemetry` gives a useless result.

This is a bug in the binding between source code and the website that gets loaded when you press F1. It should be strongly correlated based on assembly and fully qualified type name, but it's not.

> Problem 2: Googling "MetricTelemetry" gives two top results, one on [MSDN](https://msdn.microsoft.com/en-us/library/microsoft.applicationinsights.contracts.metrictelemetry.aspx) and one on [docs](https://docs.microsoft.com/en-us/dotnet/api/microsoft.applicationinsights.datacontracts.metrictelemetry), neither of which make clear what code they apply to ...

This is a problem with the templates for the documentation websites. They need to make clear what assembly and version they're talking about.

> Problem 3: The IntelliSense docs on `MetricTelemetry` don't say what to do with `Value` when using statistics. Presumably, it should be the mean, but it would be nice if the intent were documented.

This is about improving docs in TrackMetric.

> Problem 4: There's no support for calculating the statistical properties, or if there are, the IntelliSense or other docs in `MetricTelemetry` don't link to it, so it's not discoverable.

This is a feature request. IIRC, when I went digging, it seemed like the functionality may already be implemented, but not in a way that is available to the developer.

> Problem 5: Even if you calculate the statistics, they don't show up when you view the metric in Application Insights. Only `Value` is displayed.

This is a consistency issue between the app insights library and website. One would expect the members on the class to handle stats to be rolled out at the same time as the support for displaying them. At the very least, if the feature isn't fully baked, comments on the stat properties to that extent would help avoid confusion.

----

I realize that having the issues broken down individually is the most helpful for addressing them, but I thought it was worth reporting them together to provide a sense of how they all added up in this use case into a very poor developer experience. That DX factor is something to consider when determining priority of fixing the individual issues.

**Comment by Bartolomeus-649** [comment] 2017-06-01 12:45
This does not just relate to MetricTelemetry, it is symptomatic for AI as a whole.

* Lack of real useful reference documentations (No, click guides are not documentation).
* No architectural or conceptual overview, so impossible to know how AI is intended to be used in larger more complicated enterprise scenarios.
* No in-depth documentation on the "lifecycle" of things tracked by AI
* No clear definition of the terms, names and concepts used.
* No real documentation on the Telemetry Initializers, Telemetry Modules, Telemetry Processors and how they interact with each other and in what way why handle things like threads, application domains and other more intricate environments and situations.
* No real documentation on what kind of applications that are supported, only web applications with browser clients?  what about webjobs? WorkerRoles? Azure Batch? Windows Services?  WPF? Xamarin? Stored Procedures? scripts running in CosmosDB?. How would you go about using AI any of those?
* No real documentation on the client script for browsers and how it interact with AI-servers and the web server. How well does it interact with ad-blockers and other privacy and integrity protection plugins in web browsers? In which scenarios is there need for client side code for AI?
* No clear vision on how to use AI in larger more complex scenarios where you need segmentation to separate data (for example, the data for the web-api that handles B2B should not interfere with the data generated from the B2C webpages).

I could go on, but I think you get the point...There need to be real in depth documentation for developers and solution architects, as well as the more abstract overview documentation needed by Enterprise architects.

**Comment by cijothomas** [comment] 2019-10-04 01:31
Closing this as I cannot find anything actionable for this repro.  There were general comments about poor state of docs  - but its more than 2 years and docs are in better state. Please open specific issues as applicable.

**Closed by cijothomas** 2019-10-04 01:31 UTC
Labels: documentation, enhancement, metrics

**Comment by aliyoussefi** [comment] 2020-05-15 20:28
Hi, I am running into an issue with MetricTelemetry and TrackMetric for the .net version of Application Insights SDK (v2.11). It seems to be similar to the originator's concerns with setting value properties. To reproduce, create a MetricTelemetry object and set Name, Min, Max and MetricNamespace. The Max will show correctly but not Min. Happy provide screenshots or recordings if this will help.

Thank you,
Ali Youssefi (alyousse)
