### ISSUE TITLE
DependencyTelemetry object hold reference to HttpWebRequest keeping connections open in case of transmission errors

### ISSUE THREAD

**Issue by johnib** [microsoft/ApplicationInsights-dotnet#2018] opened 2020-09-02 11:19 UTC
* List of [NuGet packages](https://github.com/microsoft/ApplicationInsights-dotnet#nuget-packages) and version that you are using:

```XML
    <PackageReference Include="Microsoft.ApplicationInsights" Version="2.14.0" />
    <PackageReference Include="Microsoft.ApplicationInsights.DependencyCollector" Version="2.14.0" />
    <PackageReference Include="Microsoft.ApplicationInsights.WindowsServer" Version="2.14.0" />
    <PackageReference Include="Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel" Version="2.14.0" />
```

* Runtime version (e.g. net461, net48, netcoreapp2.1, netcoreapp3.1, etc. You can find this information from the `*.csproj` file):
`net461`

* Hosting environment (e.g. Azure Web App, App Service on Linux, Windows, Ubuntu, etc.):
Windows (application is running on Service Fabric)

### Describe the bug

* We use `ServerTelemetryChannel` which is meant to hold telemetry items in memory/disk in case there's connectivity issues with the DC endpoint.
* In such case (connectivity issue) that happened in two of my VMs, we suspect that keeping so many `DependencyTelemetry` items in memory caused cascading effects on the machine by keeping connections open, **reaching to ~30K connections**
  * The connections were left open because each `DependencyTelemetry` holds a reference to a `System.Net.Connection` object:
  ![image](https://user-images.githubusercontent.com/5327862/91972529-85a45880-ed23-11ea-93a7-7da3eee27950.png)
  * The connection objects seem to point to the actual dependency I was calling (in this case Azure Storage) and not the DC endpoint (Breeze):

  ![image](https://user-images.githubusercontent.com/5327862/91972990-26931380-ed24-11ea-9c92-35cf2d5f7cd6.png)

* Another symptom we had, is that `% GC Time` was skyrocketing from 5% **to 40% steady**, could be related to the amount of objects kept in 

### To Reproduce

There is no simple repro for this, the ask is to avoid holding reference to the `HttpWebRequest` object if possible based on its impact, when retrained for long time in memory.

**Comment by cijothomas** [comment] 2020-09-02 15:01
DependencyTelemetryModules stores the raw objects inside the telemetry for a reason. Its cleared when the DependencyTelemetry is `Track` ed. The behavior you are seeing should have no relation to the particular telemetry channel being used.

I need to investigate more on this...
From the screenshot shared, the DependencyObjects are kept in memcache, by design. If the repro occured when you had network issues, then its possible that the MemCache stored a lot of open HttpClient calls.. It'd be cleared automatically when the call ends (which could take long time if the call itself is slow), or when 100secs expires.. 

I will check more.

**Comment by johnib** [comment] 2020-09-02 18:33
Why is it important to dispose the connection after the DependencyTelemetry is tracked? Theoretically it is possible to get all the information needed by observing the request+response, without holding a reference.

Maybe you can hold a weak reference instead? which will allow the GC to collect the `Connection` objects?

**Comment by johnib** [comment] 2020-09-02 19:24
I didn't mean that the SDK should dispose, I meant that the SDK mustn't hold Connection obejects from being collected by GC.

At the moment this is the case, due to holding a reference to the Connection. 


Since so many connections were not collected and disposed due to being referenced (by the DependencyTelemetry) I believe my application could not recover (for many hours), until I restarted the nodes.

**Comment by cijothomas** [comment] 2020-09-02 19:36
mm..not sure of this yet..
SDK held on to the DepenencyTelemetry (which holds HttpRequest object containing Connection I believe), because the call did not finish. So if the httpcall was not finished, would GC be able to reclaim it anyway?

**Comment by johnib** [comment] 2020-09-02 19:58
Think of a situation where the DC endpoint is unavailable for 30m, hence the ServerTelemetryChannel would keep the DependencyTelemetry items in memory. 

Because of that, references to many HttpWebRequest objects are kept, which hold the GC from collecting them (and the Connection objects as a consequence) for long time, even though the dependency request itself to the storage account have ended (with success, failure or timeout).

**Comment by cijothomas** [comment] 2020-09-02 20:05
There is no connection between ServerTelemetryChannel and this. No telemetry is collected from SDK's call to Ingestion endpoint.

**Comment by cijothomas** [comment] 2020-09-02 21:53
Update:
Between the time httpclient makes start callback and end callback, depenencytelemetry (with HttpWebRequest inside it) is held in cache. The above issue is occuring because HttpClient .NET framework is missing to the fire the end callback in certain situations like client side timeouts/dns/etc, which cause Application Insights to keep the dependencytelemetry item in MemoryCache.
This is a known issue. There is automatic cleanup after 100 sec.

There are no fixes planned in .NET Framework to address this (see below issue). This is not an issue in .NET Core. Closing as no action for the SDK.

Runtime issue link: https://github.com/dotnet/runtime/pull/33732

**Closed by cijothomas** 2020-09-02 21:53 UTC
Labels: bug
