### ISSUE TITLE
Dependency telemetry type displayed as SQL in Azure Portal when logged with parameterless overload

### ISSUE THREAD

**Issue by pakrym** [Microsoft/ApplicationInsights-dotnet#405] opened 2017-01-03 17:02 UTC
Steps to reproduce:
1. Reference `"Microsoft.ApplicationInsights.AspNetCore": "2.0.0-*",` to get ` Microsoft.ApplicationInsights (>= 2.2.0)` as dependency.
2. Use `public void TrackDependency(string dependencyName, string commandName, DateTimeOffset startTime, TimeSpan duration, bool success)` overload to track telemetry
3. Setup Azure Application and run it to get telemetry logged.

**Expected**:
Telemetry type in Azure Portal: Other/Empty

**Actual:**
Telemetry type in Azure Portal: Sql

**Note**
No value for type is displayed in VS

@SergeyKanzhelev @dnduffy

**Comment by cijothomas** [comment] 2017-01-20 23:02
![image](https://cloud.githubusercontent.com/assets/5232798/22168437/72c81d1e-df21-11e6-9f7d-26fc5aeffd0a.png)

This is reproed, Not an SDK issue i think. Should be handled by AI Backend.

**Comment by cijothomas** [comment] 2017-01-20 23:26
Confirmed this is a AI Backend processing bug. SDK is doing the correct this. Will close this issue now, and open a internal work item to fix the backend.

**Closed by cijothomas** 2017-01-20 23:26 UTC
Labels: bug

**Comment by shkrishms** [comment] 2017-06-06 19:55
Hi,
I still notice duplicate tracking. Is this resolved?

**Comment by cijothomas** [comment] 2017-06-06 21:22
@shkrishms can you elaborate on the duplicate tracking ? This issue was about AI backend marking dependency type as SQL by default, and it is fixed. Do you still see this issue or another issue where duplicate dependency entry was found?

**Comment by shkrishms** [comment] 2017-06-06 22:07
No, the same issue. see below snapshot. There is just 1 sql call, but it shows up as 2 entries.

![image](https://user-images.githubusercontent.com/25833342/26854094-84f38eba-4ac9-11e7-8716-0d1b2dc63313.png)

![image](https://user-images.githubusercontent.com/25833342/26854167-da3e8262-4ac9-11e7-8d3a-2bbebd4bdf79.png)

**Comment by cijothomas** [comment] 2017-06-12 22:11
This issue is not about duplicates. Its about AI backend marking dependency type as SQL by default.

From the screenshot, it looks like 2 dependencies collected are separate - i see different id and time.
