### ISSUE TITLE
[Metrics] Metrics aggregation should respect sampleRate in case it was later than sampling module in the pipe

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-dotnet#492] opened 2017-03-30 18:30 UTC
If metrics aggregation processor placed after sampling module - it should respect `samplingRate` field to calculate metrics.

**Comment by SergeyKanzhelev** [comment] 2017-03-30 18:34
cc: @macrogreg

**Comment by macrogreg** [comment] 2017-04-05 18:01
Metrics aggregation is explicitly designed to run before any filters. Otherwise it looses it's point. If users manually add some raw telemetry filtering before the metric extraction, we will not be able to extract correct metrics anyway. This applies to any kind of filtering, including our sampling module.
Closing as By Design.

**Closed by macrogreg** 2017-04-05 18:01 UTC
Labels: bug
