### ISSUE TITLE
Adaptive Sampler not working as expected

### ISSUE THREAD

**Issue by vishweshbankwar** [microsoft/ApplicationInsights-dotnet#2742] opened 2023-02-03 00:28 UTC
* List of [NuGet packages](https://github.com/microsoft/ApplicationInsights-dotnet#nuget-packages) and version that you are using:
 * "Microsoft.ApplicationInsights.WorkerService" Version="2.21.0"

### Describe the bug
Adaptive sampler when used with activities with `Recorded` flag set to `true` (in case of OpenTelemetry this could be set via AlwaysOnSampler) results in high number of telemetry records to be ingested compared to activities with the flag set to `false`

### To Reproduce
```csharp
internal class Program
    {
        static void Main(string[] args)
        {
            TelemetryConfiguration configuration = TelemetryConfiguration.CreateDefault();
            configuration.TelemetryInitializers.Add(new OperationCorrelationTelemetryInitializer());
            configuration.TelemetryChannel = new CustomChannel();
            configuration.InstrumentationKey = "ikey";
            var telemetryClient = new TelemetryClient(configuration);

            // Sampling
            var builder = configuration.DefaultTelemetrySink.TelemetryProcessorChainBuilder;
            builder.UseAdaptiveSampling();
            builder.Build();

            while (true)
            {
                for (int i = 0; i < 10000; i++)
                {
                    Activity act = new Activity("Parent");
                    // uncomment the following line to see more telemetryitems
                    // act.ActivityTraceFlags |= ActivityTraceFlags.Recorded;
                    act.Start();
                    var startTime = DateTime.UtcNow;
                    var timer = System.Diagnostics.Stopwatch.StartNew();
                    timer.Stop();
                    telemetryClient.TrackDependency("myDependencyType", "myDependencyCall", "myDependencyData", startTime, timer.Elapsed, true);

                    act.Stop();
                }
                telemetryClient.Flush();
                Thread.Sleep(1000);
            }
        }
    }
```

CustomChannel
```csharp
internal class CustomChannel : ITelemetryChannel
    {
        public bool? DeveloperMode { get; set; } = true;
        public string EndpointAddress { get; set; } = "endpoint";

        static long telemetryCount = 0;

        public void Dispose()
        {
        }

        public void Flush()
        {
            Console.WriteLine("TelemetryCount: " + telemetryCount);
        }

        public void Send(ITelemetry item)
        {
            telemetryCount++;
        }
    }
```

**Comment by vishweshbankwar** [comment] 2023-02-08 00:17
For anyone encountering this, the workaround is to use Fixed rate sampling instead of Adaptive.

**Comment by vishweshbankwar** [comment] 2023-04-13 21:10
Beta package is now available with the fix https://www.nuget.org/packages/Microsoft.ApplicationInsights/2.22.0-beta3

**Comment by OsmondJiang** [comment] 2023-04-17 03:31
@vishweshbankwar do you know when will this fix be shipped to a stable version?

**Comment by TimothyMothra** [comment] 2023-04-18 17:24
Hi @OsmondJiang, we're targeting end of May for the next stable release.

**Comment by cijothomas** [comment] 2023-05-17 04:42
Closing as the issue is fixed  https://github.com/microsoft/ApplicationInsights-dotnet/issues/2742#issuecomment-1507613660

**Closed by cijothomas** 2023-05-17 04:42 UTC
Labels: bug
