### ISSUE TITLE
ApplicationInsights locking up network ports/sockets?

### ISSUE THREAD

**Issue by kanadaj** [microsoft/ApplicationInsights-dotnet#850] opened 2018-06-29 11:35 UTC
Hi guys,

I've been struggling this for a while, and I can almost completely confirm it, as I've no managed to reproduce the issue without Application Insights - it seems that over time, AI (most likely it's the profiler) locks up out web application's sockets/threads over time, causing non-sense like this to appear:

```
StackExchange.Redis.RedisConnectionException
No connection is available to service this operation: GET chapters:228901; It was not possible to connect to the redis server(s); ConnectTimeout; IOCP: (Busy=3,Free=997,Min=4,Max=1000), WORKER: (Busy=75,Free=948,Min=4,Max=1023), Local-CPU: n/a
```

Along with Entity Framework connection timeouts, which usually cause the request itself to time out.

Restarting the application usually mitigates this, but then it comes back. I've managed to reproduce this both in ASP.NET Core and ASP.NET MVC 5.

Reproducing this artificially is very hard, since we have a moderately large website with a few millions of pageviews per day, and the error surfaces anywhere from 24 hours to a week.

Based on my experiments, the NuGet package isn't actually required for reproduction, only the Azure Extension.

## Version Info 
SDK Version : v2.3.0
.NET Version :	Core 2.1.1.0					
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) :Azure Extension, NuGet
OS : Windows Server
Hosting Info (IIS/Azure WebApps/ etc) : Azure WebApp

**Comment by flagbug** [comment] 2018-07-09 19:03
I guess this is the same root cause as https://github.com/Microsoft/ApplicationInsights-dotnet/issues/594?

**Comment by cijothomas** [comment] 2018-07-09 19:23
#594 is fixed, and will be released as a beta this week.

Have you faced this issue in .net runtime 2.1 or 2.0? I have consistent repro in 2.1. You can try to run an app which continuously creates HttpClient instances and makes some outbound call and see whether the issue repros.

**Comment by kanadaj** [comment] 2018-07-11 13:41
Only tried 2,1 so not sure about 2.0. But it is possible, though weird - if every connection opened a new connection via HttpClient that'd mean thousands of connections per minute in this case and I doubt the app would last more than an hour like that, but it only came down after 24 hours somehow...

**Comment by SergeyKanzhelev** [comment] 2018-07-11 16:02
There are buffering in place. So up to three connections per minute in medium-load apps. So it may last 24 hours

**Comment by cijothomas** [comment] 2020-04-08 18:49
Closing old issues without repro. HttpClient is now re-used, and channel makes upto 10 connections at a point.

**Closed by cijothomas** 2020-04-08 18:49 UTC
Labels: bug
