### ISSUE TITLE
WorkerService configuration not working same as ASP.NET Core configuration

### ISSUE THREAD

**Issue by Euphoric** [microsoft/ApplicationInsights-dotnet#1725] opened 2020-03-11 08:39 UTC
**Describe your environment.** Describe any aspect of your environment relevant to the problem:
* SDK version: 3.1
* .NET runtime version (.NET or .NET Core, TargetFramework in the .csproj file): Core 3.1
* Hosting Info (IIS/Azure WebApps/etc): Console/Kestrel
* Platform and OS version: Windows 10

**Steps to reproduce.**
In ASP.NET Core application, when using NuGet `Microsoft.ApplicationInsights.AspNetCore 2.13.1` and using `services.AddApplicationInsightsTelemetry();` and using appsettings.json : 
```
{
  "Logging": {
    "LogLevel": {
      "Default": "Debug"
    },
    "ApplicationInsights": {
      "LogLevel": {
        "": "Debug"
      }
    }
  },

  "ApplicationInsights": {
    "InstrumentationKey": "key ommited"
  }
}
```
Then Debug and Information logs are sent to AI correctly.

In a console application, using NuGet `Microsoft.ApplicationInsights.WorkerService 2.13.1` and using `services.AddApplicationInsightsTelemetryWorkerService();` and using same appsettings.json as above, the **Debug and Information logs are not sent**. The `Logging:ApplicationInsights:LogLevel` doesn't seem to be taken into account. I would expect same configuration to result in same behavior for ASP.NET Core and WorkerService.

**Additional context.**
I've tried with version 2.14.0-beta3 and problem is still there.
Adding `loggingBuilder.AddFilter<Microsoft.Extensions.Logging.ApplicationInsights.ApplicationInsightsLoggerProvider>("", LogLevel.Debug);` to the console application does cause Debug and Information to be sent, but this is not changeable through configuration.

**Comment by cijothomas** [comment] 2020-03-11 16:43
Is you application a pure console app? Or did you use the Worker project template?
For pure console apps, appsettings.json is not parsed - Did the instrumentation get picked up from the appsettings.json? I'd expect neither ikey nor logger setting would get picked up automatically from appsettings.json in a console application.  In Worker template, the default hostbuilder adds appsettings.json as one of the config provider by default, and hence Appinsights too picks it up.

For now the workaround for you is to apply filtering rules in code. Its definitely possible to read the same from appsettings.json as well, but i need to find a working sample for the same.

**Comment by cijothomas** [comment] 2020-03-11 16:45
https://docs.microsoft.com/en-us/azure/azure-monitor/app/worker-service#net-corenet-framework-console-application The official docs has console app example, which calls out this limitation.

**Comment by cijothomas** [comment] 2020-03-11 17:36
Since this is not a bug, and the known limitation is documented, I'll close this issue.
Please reopen if more information is required.

**Closed by cijothomas** 2020-03-11 17:36 UTC
Labels: bug

**Comment by Euphoric** [comment] 2020-03-12 07:45
@cijothomas Sorry, but you are wrong. First, I have included code that loads appsettings.json in my console application. Same way as ASP.NET Core is setup :

```
            var builder = new ConfigurationBuilder()
                .AddJsonFile("appsettings.json", optional: false, reloadOnChange: false)
                .AddJsonFile($"appsettings.{environmentName}.json", true)
                .AddEnvironmentVariables();

            var configuration = builder.Build();

            services.AddSingleton<IConfiguration>(configuration);
```

Application Insights does then use `IConfiguration `to load it's configuration from provided appsettings.json, as it does load the `InstrumentationKey `from it. Meaning, it does load the key, but doesn't load the logging configuration.

Please, re-open this question and address it properly.

**Comment by cijothomas** [comment] 2020-03-12 14:10
Logging is not setup to read logging config from appsettings.json.  Again, its done in worker template/asp.net core, but not in console. You need to manually add it.

https://github.com/aspnet/MetaPackages/blob/f245512f6e68d65309b65528d479f32b34c67718/src/Microsoft.AspNetCore/WebHost.cs#L180

**Comment by Euphoric** [comment] 2020-03-12 16:51
@cijothomas Thank you. I din't realize whole Logging section wasn't loaded from appsettings.json . That one line fixed it.
