### ISSUE TITLE
[Metrics] Long blocking time in Metric.Track

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-dotnet#494] opened 2017-03-30 19:57 UTC
Reported by @qubitron:

> I was looking at profiler on fabrikamProd today and saw that we spent 400ms in a spinlock within the “SimpleMetricStatisticsAggregater.Track” function. Wondering if this is a known performance issue with the app insights sdk?

![image](https://cloud.githubusercontent.com/assets/9950081/24523576/55f09b96-1548-11e7-8887-f74c68991c07.png)

![image](https://cloud.githubusercontent.com/assets/9950081/24523583/5b0ee128-1548-11e7-9048-9794ca5df1b1.png)

**Comment by macrogreg** [comment] 2017-04-05 18:05
This is really not a Bug but a performance penalty related to using this new feature. We should certainly investigate it and under what specific circumstances it occurs. However, I would consider this not clocking for 2.4-Beta1. Agreed?

**Comment by MS-TimothyMothra** [comment] 2018-04-19 21:26
@macrogreg will this be replaced with your new code? If so can we close this issue?

**Comment by macrogreg** [comment] 2018-04-19 21:28
Yes this will be replaced with the new code, but it has not happened yet. You can close this now or keep it open until the replacement happened.

**Closed** 2018-04-19 21:29 UTC
Labels: bug, metrics
